project_id = "atizmwsokehhxclbckfr"

[functions.sales-strategist]
verify_jwt = false

[functions.conversation-analyzer]
verify_jwt = false

[functions.persona-generator]
verify_jwt = false

[functions.sequence-generator]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false


[functions.admin-credentials]
verify_jwt = false

[functions.bulk-import-users]
verify_jwt = false

[functions.bulk-reset-password]
verify_jwt = false

[functions.ai-mentor-chat]
verify_jwt = false

[functions.generate-commitment-copy]
verify_jwt = false

[functions.instagram-profile-generator]
verify_jwt = false

[functions.ad-creator]
verify_jwt = false
