// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fucghvojmptamtloggae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1Y2dodm9qbXB0YW10bG9nZ2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4OTcxODAsImV4cCI6MjA4NzQ3MzE4MH0.OKDWIyd110p6lJCv01cY6Ez0AQ6gg-MgGoH2PKgpqyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});